### PR TITLE
fix: allow finalizer to cleanup to continue on error (fixes #173)

### LINKED ISSUE #173: FeatureFlagSetLD fails to delete when referencing a non-existing secret
**Describe the bug**
Creating a FeatureFlagSetLD with a reference to a secret that doesn't exist results in the inability to delete the FeatureFlagSetLD resource.

**To Reproduce**
1. Create test namespace `kubectl create ns test`
2. Prepare FeatureFlagSetLD that references a non-existent secret:
```sh
$ cat test-ffsld.yaml 
apiVersion: deploy.razee.io/v1alpha2
kind: FeatureFlagSetLD
metadata:
  name: test-ffsld
  namespace: test
spec:
  sdkKeyRef:
    valueFrom:
      secretKeyRef:
        name: ld-bogus-key
        key: ld-sdk-key
```
3. Create the invalid FeatureFlagSetLD
```sh
$ kubectl create -f test-ffsld.yaml
```
4. Try and delete the FeatureFlagSetLD
```sh
$ kubectl delete -f test-ffsld.yaml --wait=false
```
5. Observe that the deletionTimestamp is set, and the featureflagset controller never removes the finalizer `client.featureflagset.deploy.razee.io`:
```
$ kubectl -n test get ffsld -o yaml
apiVersion: v1
items:
- apiVersion: deploy.razee.io/v1alpha2
  kind: FeatureFlagSetLD
  metadata:
    annotations:
      deploy.razee.io/data-hash: 06675bbcec328ebdac7259e879483f91a296b6de
    creationTimestamp: 2021-01-20T21:12:46Z
    deletionGracePeriodSeconds: 0
    deletionTimestamp: 2021-01-20T21:13:25Z
    finalizers:
    - client.featureflagset.deploy.razee.io
    generation: 2
    name: test-ffsld
    namespace: test
    resourceVersion: "53804004"
    selfLink: /apis/deploy.razee.io/v1alpha2/namespaces/test/featureflagsetsld/test-ffsld
    uid: e35552fd-3dd0-4ab2-a4e3-c67ed1096acf
  spec:
    sdkKeyRef:
      valueFrom:
        secretKeyRef:
          key: ld-sdk-key
          name: ld-bogus-key
  status:
    deploy.razee.io/finalizer-cleanup: running
    razee-logs:
      error:
        44d223594d33d3498918ed73d5de3ee1ea3b2f88: 404 - {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets
          \"ld-bogus-key\" not found","reason":"NotFound","details":{"name":"ld-bogus-key","kind":"secrets"},"code":404}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Expected behavior**
Non-existent dependencies for a resource should not prevent its deletion. When I request the deletion of the FeatureFlagSetLD the corresponding razee controller should remove its finalizer and allow deletion to finish.

**Screenshots**
N/A

**Kubernetes Version (kubectl version):**
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15+IKS", GitCommit:"434eee04daa6546e81c6d3240ffe6bcdf642cf1d", GitTreeState:"clean", BuildDate:"2020-11-25T21:25:42Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
We did not test this, but are concerned this issue may exist in other Razee CRDs. Please check this.

### PR DESCRIPTION
**Pull request by alewitt2**
currently finalizer cleanup will never continue when this._getSdkKey errors. In this case, a keyref pointing to a key/secret that doesnt exist will cause finalizer cleanup to fail forever. I considered narrowing the scope of error that we allow to be skipped, but for now am just leaving it wide open until more time is availbe to decide on a better subset of error codes that we should allow skipping on. I believe the only side effects of this, is after a while, if there are a lot of keys that dont get cleaned up, we end up leaving open a lot of open conections to LD. In most cases this shouldnt be an issue since it is rare to use a bunch of different sdk keys, and even rarer to try to clean them all up and have issues before the pod gets restarted and all connections are closed anyways.

### CODE REVIEW

**Review by acbodine — DISMISSED** [review]

**Review by mckaymic — APPROVED** [review]
At some point we should clean up this logic a bit.  The code currently uses exceptions to catch know, expected behaviour (not just to catch something unexpected).

File: src/FeatureFlagSetLDController.js [hunk 1]
```diff
@@ -212,14 +212,38 @@ module.exports = class FeatureFlagSetLDController extends BaseController {
...
     let instanceUid = objectPath.get(this.data, ['object', 'metadata', 'uid']);
-    let sdkkey = await this._getSdkKey();
+    let sdkkey;
+    try {
+      sdkkey = await this._getSdkKey();
+    } catch (e) {
+      this.log.warn(`Failed to get sdk key from kube-api during ${this.name}'s finalizer cleanup. resorting to table lookup.`, e);
+      sdkkey = this._getSdkKeyFromDict(instanceUid);
+      if (sdkkey === undefined) {
+        this.log.debug('No sdkkey found in table lookup, skipping cleanup since sdkkey isnt associated with a client.');
```
Comment (adamkingit) [inline src/FeatureFlagSetLDController.js:238]:
```suggestion
        this.log.debug('No sdkkey found in table lookup, skipping cleanup since sdkkey is not associated with a client.');
```

File: src/FeatureFlagSetLDController.js [hunk 2]
```diff
@@ -212,14 +212,38 @@ module.exports = class FeatureFlagSetLDController extends BaseController {
...
+        return;
+      }
+    }
     objectPath.del(clients, [sdkkey, 'instances', instanceUid]);
 
     if (Object.keys(objectPath.get(clients, [sdkkey, 'instances'], {})).length == 0) {
       this.log.debug(`Closing client ${sdkkey}`);
-      let client = objectPath.get(clients, [sdkkey, 'client'], { close: () => {} });
+      let client = objectPath.get(clients, [sdkkey, 'client'], { close: () => { } });
```
Comment (adamkingit) [inline src/FeatureFlagSetLDController.js:246]:
```suggestion
      const client = objectPath.get(clients, [sdkkey, 'client'], { close: () => { } });
```

File: src/FeatureFlagSetLDController.js [hunk 3]
```diff
@@ -212,14 +212,38 @@ module.exports = class FeatureFlagSetLDController extends BaseController {
...
+    const sdkKeys = Object.keys(clients);
+    for (let i = 0; i < sdkKeys.length; i++) {
+      const sdkKey = sdkKeys[i];
+      const instanceUids = Object.keys(objectPath.get(clients, [sdkKey, 'instances']));
+      for (let j = 0; j < instanceUids.length; j++) {
+        const uid = instanceUids[j];
+        if (uid === instanceUid) {
+          return sdkKey;
+        }
+      }
```
Comment (adamkingit) [inline src/FeatureFlagSetLDController.js:225]: const idIndex=instanceUids.indexOf(instanceUid);
if (idIndex !== -1) {
  return sdkKey;
}

File: src/FeatureFlagSetLDController.js [hunk 4]
```diff
@@ -212,14 +212,35 @@ module.exports = class FeatureFlagSetLDController extends BaseController {
     };
   }
 
+  _getSdkKeyFromDict(instanceUid) {
+    const sdkKeys = Object.keys(clients);
+    for (let i = 0; i < sdkKeys.length; i++) {
```
Comment (adamkingit) [inline src/FeatureFlagSetLDController.js:217]:
```suggestion
    for (const i = 0; i < sdkKeys.length; i++) {
```

Comment (alewitt2) [reply src/FeatureFlagSetLDController.js:217]: cant declare const in a for loop

**Review by adamkingit — APPROVED** [review]
